version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    ports:
      - "8001:80"            
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: payment_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"          
    volumes:
      - payment_db_data:/var/lib/mysql

volumes:
  payment_db_data:
